version: '3.9'

services:
  db:
    env_file: 
     - ./config.env
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: 
      - postgres
      - -c
      - max_connections=500
    ports:
      - ${DB_PORT}:5432
    volumes:
      - wallet_data:/var/lib/postgresql/data
      - ./internal/db/migrations:/docker-entrypoint-initdb.d
    networks:
      - app-network

  redis:
    env_file: 
      - ./config.env
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - app-network

  app:
    build: .
    env_file: 
      - ./config.env
    volumes:
      - ./config.env:/app/config.env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      - PORT=${APP_PORT}
      - REDIS_ADDR=redis:${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  wallet_data:
